replace `1' = "Agricultural, farming, fishing, forestry" if `1' == "03"
replace `1' = "Petroleum products, fuel, electricity and other sources of energy" if `1' == "09"
replace `1' = "Mining and basic metals" if `1' == "14"
replace `1' = "Food, beverages and tobacco" if `1' == "15"
replace `1' = "Agricultural machinery" if `1' == "16"
replace `1' = "Clothing, footwear and luggage articles" if `1' == "18"
replace `1' = "Leather and textile fabrics, plastic and rubber materials" if `1' == "19"
replace `1' = "Printed matter and related products" if `1' == "22"
replace `1' = "Chemical products" if `1' == "24"

replace `1' = "Office and computing machinery" if `1' == "30"
replace `1' = "Electrical machinery, apparatus, equipment and consumables; Lighting" if `1' == "31"
replace `1' = "Radio, television, communication, telecommunication" if `1' == "32"
replace `1' = "Medical equipments, pharmaceuticals and personal care products" if `1' == "33"
replace `1' = "Transport equipment and auxiliary products to transportation" if `1' == "34"
replace `1' = "Security, fire-fighting, police and defence equipment" if `1' == "35"
replace `1' = "Musical instruments, sport goods, games, toys, handicraft, art materials and accessories" if `1' == "37"
replace `1' = "Laboratory, optical and precision equipments (excl. glasses)" if `1' == "38"
replace `1' = "Furniture (incl. office furniture), furnishings, domestic appliances (excl. lighting) and cleaning products" if `1' == "39"

replace `1' = "Collected and purified water" if `1' == "41"
replace `1' = "Industrial machinery" if `1' == "42"
replace `1' = "Machinery for mining, quarrying, construction equipment" if `1' == "43"
replace `1' = "Construction structures and materials; auxiliary products to construction (excepts electric apparatus)" if `1' == "44"
replace `1' = "Construction work" if `1' == "45"

replace `1' = "Software package and information systems" if `1' == "48"
replace `1' = "Repair and maintenance services" if `1' == "50"
replace `1' = "Installation services (except software)" if `1' == "51"
replace `1' = "Hotel, restaurant and retail trade services" if `1' == "55"
replace `1' = "Transport services (excl. Waste transport)" if `1' == "60"
replace `1' = "Supporting and auxiliary transport services; travel agencies services" if `1' == "63"
replace `1' = "Postal and telecommunications services" if `1' == "64"
replace `1' = "Public utilities" if `1' == "65"
replace `1' = "Financial and insurance services" if `1' == "66"
replace `1' = "Real estate services" if `1' == "70"
replace `1' = "Architectural, construction, engineering and inspection services" if `1' == "71"
replace `1' = "IT services: consulting, software development, Internet and support" if `1' == "72"
replace `1' = "Research and development services and related consultancy services" if `1' == "73"
replace `1' = "Administration, defence and social security services" if `1' == "75"
replace `1' = "Services related to the oil and gas industry" if `1' == "76"
replace `1' = "Agricultural, forestry, horticultural, aquacultural and apicultural services" if `1' == "77"
replace `1' = "Business services: law, marketing, consulting, recruitment, printing and security" if `1' == "79"
replace `1' = "Education and training services" if `1' == "80"
replace `1' = "Health and social work services" if `1' == "85"
replace `1' = "Sewage-, refuse-, cleaning-, and environmental services" if `1' == "90"
replace `1' = "Recreational, cultural and sporting servicesOther community, social and personal services" if `1' == "92"
replace `1' = "Other community, social and personal services" if `1' == "98"
replace `1' = "" if `1' == "99"